<div class="ta-center bottom-pad-10px">
	<a href="#" class="gradient button-green">Add Customer</a>
</div>
<table class="list">
	<thead>
		<tr>
			<th style="width:24px;"><input type="checkbox" name="select-all" /></th>
			<th>Customer Name</th>
			<th>Vat Number</th>
			<th>Due</th>
			<th>Total</th>
			<th class="no-border trans-bg" style="width:16px;"></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td style="width:24px;"><input type="checkbox" name="select-0" /></td>
			<td><a href="#">Microsoft</a></td>
			<td><a href="#">66666666Z</a></td>
			<td class="ta-right"><a href="#">100 &euro;</a></td>
			<td class="ta-right"><a href="#">1,000.00 &euro;</a></td>
			<td><a href="#" class="link-invoices">Invoices</a></td>
		</tr>
		<tr>
			<td style="width:24px;"><input type="checkbox" name="select-0" /></td>
			<td><a href="#">Apple Corp.</a></td>
			<td><a href="#">11111111A</a></td>
			<td class="ta-right"><a href="#">50 &euro;</a></td>
			<td class="ta-right"><a href="#">5,000.00 &euro;</a></td>
			<td><a href="#" class="link-invoices">Invoices</a></td>
		</tr>
	</tbody>
</table>
<div class="list-nav">
	<a href="#">First</a>
	<span class="separator">|</span>
	<a href="#">Prev</a>
	<span class="separator">|</span>
	Page 1 / 1
	<span class="separator">|</span>
	<a href="#">Next</a>
	<span class="separator">|</span>
	<a href="#">Last</a>
	<span class="separator">|</span>
	go to
	<input type="text" name="page" style="width:32px;" />
	<input type="submit" value="Go" />
</div>