<div class="ta-center bottom-pad-10px">
	<a href="<?php echo $this->url(
            	array('controller'=>'customers', 'action' => 'add')
            ); ?>" class="gradient button-green">Add Customer</a>
</div>
<?php if (count($this->paginator)) { ?>
<table class="list">
	<thead>
		<tr>
			<th style="width:24px;"><input type="checkbox" name="select-all" /></th>
			<th>Customer Name</th>
			<th>Vat Number</th>
			<th>Due</th>
			<th>Total</th>
			<th class="no-border trans-bg" style="width:16px;"></th>
		</tr>
	</thead>
	<tbody>
<?php foreach ($this->paginator as $customer){ ?>
		<tr>
			<td style="width:24px;"><input type="checkbox" name="select-0" /></td>
			<td><a href="#"><?php echo $customer['name'] ?></a></td>
			<td><a href="#"><?php echo $customer['vat_number'] ?></a></td>
			<td class="ta-right"><a href="#"><?php echo $customer['owing'] ?></a></td>
			<td class="ta-right"><a href="#">1,000.00 &euro;</a></td>
			<td><a href="#" class="link-invoices">Invoices</a></td>
		</tr>
<?php } ?>
	</tbody>
</table>
<?php } ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml'); ?>
                                    
