<table class="list">
	<thead>
		<tr>
			<th style="width:24px;"><input type="checkbox" name="select-all" /></th>
			<th>Customer Name</th>
			<th>Vat Number</th>
			<th>Due</th>
			<th>Total</th>
			<th class="no-border trans-bg" style="width:16px;"></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td style="width:24px;"><input type="checkbox" name="select-0" /></td>
			<td>Microsoft</td>
			<td>66666666Z</td>
			<td class="ta-right">100 &euro;</td>
			<td class="ta-right">1,000.00 &euro;</td>
			<td><a href="#" class="link-invoices">Invoices</a></td>
		</tr>
		<tr>
			<td style="width:24px;"><input type="checkbox" name="select-0" /></td>
			<td>Apple Corp.</td>
			<td>11111111A</td>
			<td class="ta-right">50 &euro;</td>
			<td class="ta-right">5,000.00 &euro;</td>
			<td><a href="#" class="link-invoices">Invoices</a></td>
		</tr>
	</tbody>
</table>
<div class="list-nav">
	<a href="#">First</a> | <a href="#">Prev</a> | Page 1 / 1 | <a href="#">Next</a> | <a href="#">Last</a> | goto
	<input type="text" name="page" style="width:32px;" />
	<input type="submit" value="Go" />
</div>